# Generated by Django 6.0.1 on 2026-01-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='quests.achievement'),
        ),
    ]
